name: Build and Push Docker Image

on:
  push:
    branches:
      - php-8.2 # Trigger on push to main branch
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read
  packages: write # Needed to push to GitHub Container Registry
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        PROJECT_NAME=$(basename ${{ github.repository }})
        docker build -t ghcr.io/${{ github.repository_owner }}/php-weblankan:8.2-apache ./php-8.2-apachie

    # Push the Docker image
    - name: Push Docker image
      run: |
        PROJECT_NAME=$(basename ${{ github.repository }})
        docker push ghcr.io/${{ github.repository_owner }}/php-weblankan:8.2-apache